#!/usr/bin/env ansible-playbook

- name: green-proxy
  hosts: superset
  become: true
  tasks:
    - name: Create /opt/green-proxy directory if it does not exist
      file:
        path: /opt/green-proxy
        state: directory

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes

    - name: Preinstallation process
      package:
        name:
          - ca-certificates

    - name: Copy binary to /opt/green-proxy
      copy:
        src: ./bin/proxy-runner-lin64
        dest: /opt/green-proxy/proxy-runner-lin64
        mode: +x

    - name: Copy service definition to /etc/systemd/sytem
      copy:
        src: ./config/green-proxy.service
        dest: /etc/systemd/system/green-proxy.service

    - name: Starting proxy
      systemd:
        name: green-proxy
        enabled: yes
        state: started
        daemon_reload: yes
