#!/usr/bin/env ansible-playbook

- name: green-proxy
  hosts: green-proxy
  become: true
  tasks:
    - name: Create project directory and copy everything
      synchronize:
        src: ./
        dest: ~/green-proxy
        checksum: true

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes

    - name: Preinstallation process
      package:
        name:
          - ca-certificates
          - curl

    - name: Download Go 1.18 package
      get_url:
        url: https://go.dev/dl/go1.18beta1.linux-amd64.tar.gz
        dest: /home/ktrn

    - name: Unpack Go package
      unarchive:
        src: /home/ktrn/go1.18beta1.linux-amd64.tar.gz
        dest: /home/ktrn
        remote_src: yes

    - name: Export paths to build 1
      shell:
        cmd: "export GOROOT=/go"

    - name: Export paths to build 2
      shell:
        cmd: "export GOPATH=/go"

    - name: Export paths to build 3
      shell:
        cmd: "export PATH=$GOPATH/bin:$GOROOT/bin:$PATH"

    - name: Build proxy
      shell:
        cmd: "cd ~/green-proxy && go build -o test-proxy"
