#!/usr/bin/env ansible-playbook

- name: green-proxy
  hosts: green-proxy
  become: true
  tasks:
    - name: Create /etc/green-proxy directory if it does not exist
      file:
        path: /etc/green-proxy
        state: directory

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes

    - name: Preinstallation process
      package:
        name:
          - ca-certificates

    - name: Copy binary to /etc/green-proxy
      copy:
        src: ./bin/proxy-runner-lin64
        dest: /etc/green-proxy/proxy-runner-lin64

    - name: Giving proxy permission
      shell:
        cmd: 'chmod +x /etc/green-proxy/proxy-runner-lin64'

    - name: Copy service definition to /etc/systemd/sytem
      copy:
        src: ./config/green-proxy-linux.service
        dest: /etc/systemd/system/green-proxy.service

    - name: Starting proxy
      systemd:
        name: green-proxy
        enabled: yes
        state: started
        daemon_reload: yes
